### ISSUE TITLE
Docs for esda not reachable 

### ISSUE THREAD

**Issue by phloose** [pysal/esda#107]
When trying to access the docs on [esda.readthedocs.io](https://esda.readthedocs.io) "Not found" is returned. I followed the link to the docs from this repos [documentation badge](https://esda.readthedocs.io/en/latest/?badge=latest) and also that from the [documentation section](http://pysal.org/documentation) on the official pysal homepage (pysal.org) but both point to a blank page with "Not found" on it.

**Comment by sjsrey** [comment]
Thanks for reporting. 
We will update the links to point to the new home for the esda documentation: https://pysal.org/esda/
