### ISSUE TITLE
joint_counts chi_2 failing

### ISSUE THREAD

**Issue by sjsrey** [pysal/esda#109]
When testing esda against master in libpysal,  one [test](https://travis-ci.org/pysal/esda/jobs/653937197#L872) is failing due to a change in https://github.com/pysal/libpysal/commit/9a303797dc68ad0db2c339ef54c2270a5950b5cc#diff-e8a3363e7d0110431da1549a5428007b having to do with what `.w.to_adjlist(remove_symmetric=True)` returns. Because the focal units that are now returned are different than before the change, what was a bw join becomes a wb and the contingency table changes from:

[[10, 4], [0, 10]] 
before the change, to:

[[10, 3], [1, 10]]
after the change.

The fix will be to update the test in [esda](https://github.com/pysal/esda/blob/master/tests/test_join_counts.py#L37) once a new version of libpysal gets released.

**Comment by jGaboardi** [comment]
Test fixed and passing.
