### ISSUE TITLE
G_Local returns unexpectedly low z_sim for what should be a hotspot

### ISSUE THREAD

**Issue by phloose** [pysal/esda#112]
```
pysal: 2.1.0
pysal.explore.esda: 2.1.1
python: 3.8.2 from miniconda3
os: Pop!_OS/Ubuntu 19.10 but also applies to windows 10 1909
```

I have come across a weird issue while trying to use the `pysal.explore.esda.G_Local` implementation with permutations to find local hot-/coldspots in several datasets. 

The computed z_sim for a features attribute that by natural expectation should be a hotspot (because has really high numbers compared to the near neighborhood and much higher difference to the more far neighborhood) is much to low. It feels like a pattern that especially features with very large attribute differences to its neighborhood get a low z_sim value. They are often remarkably framed by statistically significant values.

Then i also found a [QGIS plugin for hotspot analysis](https://github.com/danioxoli/HotSpotAnalysis_Plugin) which uses an old version of pysal (1.14.3). There the hotspot analysis works as expected and returns high z_sim values for expected hotspots (see below example for corona cases in Hamburg) 

I compute the G_Local like so:

```python
import fiona
import numpy as np
from libpysal.weights import Queen  # in pysal 1.14.3: from pysal.weights import Queen
from pysal.explore.esda import G_Local  # in pysal 1.14.3: from pysal.esda import G_Local

with fiona.open("RKI_Corona_Landkreise.shp") as inp:
    features = list(inp)

y = np.array([feature["properties"]["cases"] for feature in features])
w = Queen.from_shapefile("RKI_Corona_Landkreise.shp")

np.random.seed(12345)
g = G_Local(y, w, star=True, transform="r", permutations=999)
```

For testing:
The last dataset i used was from the german [Robert-Koch-Insitut for the current status of the corona pandemic on county level in germany](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0?selectedAttribute=cases7_per_100k). I used the **cases** attribute and as there are several hotspots just by knowing from the media and by just comparing the numbers i expected especially _Hamburg_, _Heinsberg_ and _Köln_ as hotspots (there are some more in the southern part of germany but for brevity lets focus on the named). What is striking now is that these "hotspots from knowledge" are statistically not significant, despite they should be, but are framed by other statistically significant hotspots.
 
A numeric example for Hamburg (index 15 of z_sim array)
* PySAL 1.14.3 returns **z_sim 2.82** for Hamburg
* PySAL 2.1.0/PySAL explore esda 2.1.1 returns  **z_sim -0.21** for Hamburg (!)

The Zs values are all equal only the z_sim values are really different

Another dataset i used is [an official census dataset from 2011 on county level](https://opendata-esri-de.opendata.arcgis.com/datasets/esri-de-content::zensus2011kreise-haushalte). There i used the attribute **L_Nichtehe** which gives the number of communities that are not marital (don't know if google translated this correctly...). Again i expected _Hamburg_,  _Berlin_ and its surroundings as hotspots as these are big cities where a lot of people are living in non-marital communities. There the same pattern like described above occurs, really high values from G_Local not "marked" as statistically significant are framed by higher values that are statistically significant.

My question is now, what changed in the `getisord` module or in the `G_Local` implementation for the calculation of simulated values? Is this a bug? Please test the datasets i linked with both versions and tell me if you can reproduce this (the corona dataset might have been updated but Hamburg should still be a hotspot). It should not be that two versions of G_Local return a different z_sim value by using the same underlying algorithm... At the moment i am a bit lost ....

**Comment by phloose** [comment]
Thanks! If you need that particular corona dataset from which i calculated the example z_sim values let me know!

**Comment by sjsrey** [comment]
Comparing the pysal (master) results with those from open geoda, the values for hamburg are identical.

For GeoDA Hamburg is not a hot-spot when using the Gstar (but it clearly is surrounded by significant observations):

![hamburg_geoda](https://user-images.githubusercontent.com/118042/79644943-055ccc80-8161-11ea-83c3-90838650d1c6.png)

Same result for PySAL:
![hamburg_pysal](https://user-images.githubusercontent.com/118042/79644957-21f90480-8161-11ea-8984-9fd5c8eed60a.png)


So my previous comment would explain why the results differ in PySAL between 1.14.3 and the current version. The current version of PySAL replicates geoda and should be used in place of  the earlier  version (1.14.3) which was used in the QGIS toolkit.

**Comment by phloose** [comment]
Thank you very much for taking time to examine my observations! I'd also prefer the most up to date versions of PySAL.

But i am still wondering why Hamburg is not "marked" as a hotspot? With regard to the cases attribute (~4000) it is clearly outstanding from its neighborhood: All "significant" high neighbors of Hamburg have cases between ~170 and 500, which separates them clearly from the outer neighbors. But Hamburg with such a high value as center from the hotspot is not a hotspot?! So why does it get such a low z-score? Am i misunderstanding something with regard to how G* works? From my intuition it does not make sense that Hamburg is not a hotspot...

Another interesting finding is that the result from pysal when visualized look different than what geoda returns:
![pysal_issue_112](https://user-images.githubusercontent.com/37411699/79670117-00c80080-81c1-11ea-9bbd-6fdc073b2d56.png)

Again thanks for taking your time to investigate in my issue!

**Comment by phloose** [comment]
>  With regard to the cases attribute (~4000) it is clearly outstanding from its neighborhood: All "significant" high neighbors of Hamburg have cases between ~170 and 500, which separates them clearly from the outer neighbors. But Hamburg with such a high value as center from the hotspot is not a hotspot?! 

@sjsrey any new insights why this is behaving in such a counterintuitive way?

**Comment by sjsrey** [comment]
I haven't had a chance this week - but will dig deeper this weekend.

**Comment by phloose** [comment]
Thanks for responding so fast! I didn't want to be stressful!

**Comment by phloose** [comment]
@sjsrey A friendly reminder :) Could you find anything, that would explain the observations?

**Comment by jeffcsauer** [comment]
To toss in a thought - could this at all be due to the impact of the Elbe the defining neighbors? I did a **very** coarse removal of the Elbe and Hamburg is now showing up 'hot' in QGIS:

![image](https://user-images.githubusercontent.com/31426294/82128833-3219f900-978c-11ea-9715-d657a03980ff.png)

A more refined trimming of the polygons might be helpful. Thoughts @phloose?

**Comment by phloose** [comment]
At first i thought this counterintuitive result might be due to the more complicated neighbor situation that is defined by the Elbe. But then i thought regardless of that one specific neighbor situation to the lower left Hamburg should be still significantly outstanding with regard to the other neighbors that share a boundary on the other sides. I never tested it the way you did now to be honest...

Did you use the QGIS plugin i mentioned in the first post? It uses an old version of PySAL that "works" correctly and shows Hamburg as a hotspot as one would expect with such a high number of cases. But as mentioned in https://github.com/pysal/esda/issues/112#issuecomment-614749078 this version should not be used anymore.

**Comment by sjsrey** [comment]
After more digging, the analytical inference in pysal (2.2.0) agrees with that in spdep
## pysal
![image](https://user-images.githubusercontent.com/118042/82130971-19f2ab80-9785-11ea-8425-6f49b9716d03.png)

## spdep
![image](https://user-images.githubusercontent.com/118042/82131026-ae5d0e00-9785-11ea-8df5-f0aa88c354f5.png)


Note that Hamburg is not a hotspot in the Gi version of the statistic, but is for the Gi* (where the focal unit is included).

The permutation based inference in pysal agrees with opengeoda. spdep doesn't implement permutation inference for the local G statistics so I can't compare there.  There is a recent paper by [Bivand and Wong (2018)](https://link.springer.com/article/10.1007/s11749-018-0599-x) that explores related issues, and may be of interest.

I don't think this result is due to a bug in implementation. It could be that inference based on local conditional permutations for the G statistics should be viewed with caution.

**Comment by phloose** [comment]
> I don't think this result is due to a bug in implementation. It could be that inference based on local conditional permutations for the G statistics should be viewed with caution.

Yeah i thought the same about the permutation inference statistics.... I found that when i don't use permutations and row standardization then i get the expected pattern (like you did above...). Why is that, i mean, why do i need to explicitly use binary weights and not row standardized weights? Maybe i need to read the respective papers again.... Thanks again for your time!

**Comment by sjsrey** [comment]
Given the origins of the G statistics with a focus on local sums (i.e., how many observations occur within a certain distance of a location), the binary weights are more intuitive. Also see [1](https://geodacenter.github.io/workbook/6a_local_auto/lab6a.html#getis-ord-statistics).

**Comment by phloose** [comment]
Ok thank you, i think we can close this now!

**Comment by sjsrey** [comment]
Ok. Thanks for raising this initially and taking the time to explore it.
