### ISSUE TITLE
Release notes for 2.3.0

### ISSUE THREAD

**Issue by sjsrey** [pysal/esda#127]
Draft [release notes](https://github.com/pysal/esda/releases/tag/untagged-64615a9d546d535a4fa1) are ready for edits/additions.

**Comment by jGaboardi** [comment]
[These](https://github.com/pysal/esda/releases/tag/untagged-64615a9d546d535a4fa1) looks good to me.

**Comment by darribas** [comment]
Editted them to add link to ADBSCAN paper repo for further context and minor edits to the conditional randomisation. Good to go afaik!

**Comment by sjsrey** [comment]
Thanks. Cutting the release.
