### ISSUE TITLE
Unexpected LISA results for polygons contained by another polygon

### ISSUE THREAD

**Issue by anitagraser** [pysal/esda#153]
As mentioned on https://gitter.im/pysal/pysal, LISA results for polygons that are completely contained within another polygon (therefore only have one neighbor) are often "not significant" even though visual inspection of the input values would suggest that they should be part of the hotspots/coldspots:

![image](https://user-images.githubusercontent.com/590385/99902665-c75bf400-2cbf-11eb-97e7-aca6b930df26.png)

![image](https://user-images.githubusercontent.com/590385/99902645-9f6c9080-2cbf-11eb-84fa-22701ddf0b4b.png)

Data and notebook to reproduce: 

https://github.com/anitagraser/pysal-temp/blob/main/notebooks/moran-local-holes.ipynb

**Comment by jGaboardi** [comment]
Possibly related to pysal/spaghetti#527.

**Comment by sjsrey** [comment]
Could you share a link to the data so we can investigate further?

**Comment by sjsrey** [comment]
I think what is going on is that the hole polygons have neighbor cardinality=1. As was discussed on [gitter](https://gitter.im/pysal/pysal?at=5fb95dbebba6a3778b7401b5), this impacts the variance of the local statistics:

![image](https://user-images.githubusercontent.com/118042/99913756-392b4200-2cae-11eb-9cab-722c8f4891bf.png)

**Comment by anitagraser** [comment]
Thank you, @sjsrey! I'll look into distance-based weights instead to try avoid this effect.
