### ISSUE TITLE
Documentation needs updating for 2.3.6

### ISSUE THREAD

**Issue by sjsrey** [pysal/esda#161]
New functionality needs to be described in:
- [api](https://pysal.org/esda/api.html)
- [ tutorial](https://pysal.org/esda/tutorial.html)

**Comment by jeffcsauer** [comment]
On my radar for LOSH, LJC, and Geary Local

(`Geary_Local` seems to be missing from the API)

**Comment by jGaboardi** [comment]
Resolved in #162.
