### ISSUE TITLE
Cannot import esda

### ISSUE THREAD

**Issue by alon-benari** [pysal/esda#165]
Importing esda from ipython cli throws:

> ----> 1 import esda

~/monocondaNew/envs/c19geo_stat/lib/python3.8/site-packages/esda/__init__.py in <module>
      5 
      6 """
----> 7 from . import adbscan
      8 from .gamma import Gamma
      9 from .geary import Geary

~/monocondaNew/envs/c19geo_stat/lib/python3.8/site-packages/esda/adbscan.py in <module>
     11 from scipy.spatial import cKDTree
     12 from collections import Counter
---> 13 from sklearn.cluster import DBSCAN
     14 from sklearn.neighbors import KNeighborsClassifier
     15 from sklearn.base import BaseEstimator as _BaseEstimator, ClusterMixin as _ClusterMixin

~/monocondaNew/envs/c19geo_stat/lib/python3.8/site-packages/sklearn/__init__.py in <module>
     79     from . import __check_build  # noqa: F401
     80     from .base import clone
---> 81     from .utils._show_versions import show_versions
     82 
     83     __all__ = ['calibration', 'cluster', 'covariance', 'cross_decomposition',

~/monocondaNew/envs/c19geo_stat/lib/python3.8/site-packages/sklearn/utils/_show_versions.py in <module>
     10 import importlib
     11 
---> 12 from ._openmp_helpers import _openmp_parallelism_enabled
     13 
     14 

ImportError: dlopen: cannot load any more object with static TLS

python 3.8
Ubuntu 14.04
ipython 7.19.0
skelarn 0.23.2
 installed esda, ipython. Seems like the issue is in DBSCAN from sklearn. ?
I reinstalled. 

Of note , the import works fine at the regular python prompt, but I had rather worked in iPython.
What am I missing here?

Thanks

**Comment by jGaboardi** [comment]
What happens when you import scikit-learn by itself? On first glance this appears to be an issue with scikit-learn, not `esda`. Also, which version of `esda` do you have installed?

**Comment by jGaboardi** [comment]
Closing due to lack of response.
