### ISSUE TITLE
[PERF] List comprehension to array operation in G_Local

### ISSUE THREAD

**Issue by TLouf** [pysal/esda#181]
I noticed `G_Local` was particularly slow even with `permutations=0`, so I looked at the code and realized the bottleneck was there:

https://github.com/pysal/esda/blob/642880e0b49913de07e5b7fafb3dd0b5855ed2ef/esda/getisord.py#L395 

which can very simply be converted to an array operation to increase performance. So I went hunting for other such list comprehensions but fortunately in other places, like where `p_z_sim` is computed, this was not overlooked, I only found this other one which doesn't have much impact I think:
https://github.com/pysal/esda/blob/642880e0b49913de07e5b7fafb3dd0b5855ed2ef/esda/geary_local_mv.py#L86

If that's ok I can write the PR myself, that should be a very simple one.

**Comment by ljwolf** [comment]
Hi, thanks for this! 

We've got a pending re-write for the entire engine for local G statistics in #133, but that has stalled for a code review for a while. That should fix the performance issue [here](https://github.com/pysal/esda/pull/133/files#diff-d6163c77c88b8e25cbd1fc7898552a57da861bf3cc13167d34188fbd7e1ad49aR420). 

if you want to fix the local multivariate Geary one, that'd be awesome! The local G will be made more performant very soon with #133

**Comment by TLouf** [comment]
Thanks for the quick reply!

> That should fix the performance issue here.

Just to make sure, do you mean you will make the change in that PR? Because for now that line has been left untouched:
https://github.com/pysal/esda/pull/133/files#diff-d6163c77c88b8e25cbd1fc7898552a57da861bf3cc13167d34188fbd7e1ad49aL395

**Comment by ljwolf** [comment]
Ah, I see! Yes, line 401 in that diff should use the same strategy as line 420.
