### ISSUE TITLE
missing values in local geary

### ISSUE THREAD

**Issue by ljwolf** [pysal/esda#194]
# the issue

@tastatham was using the local multivariate Geary for some work in his dissertation, and noticed that it was returning values even when there were missing data. 

# the cause
Upon investigating, I noticed 

1. in [Line 110](https://github.com/pysal/esda/blob/master/esda/geary_local_mv.py#L115), the `gs` array will contain `NaN`
2. These are then dropped in [line 115](https://github.com/pysal/esda/blob/master/esda/geary_local_mv.py#L115), because `temp.groupby("ID").sum()` will drop the `NaN` values during summation:
```python
import pandas, numpy
df = pandas.DataFrame(numpy.arange(10).reshape(5,2), columns=['v1','v2'])
df.loc[2,'v1'] = numpy.nan
df.loc[3,'v2'] = numpy.nan
df['group'] = df.index > 2
df
```

```
    v1   v2  group
0  0.0  1.0  False
1  2.0  3.0  False
2  NaN  5.0  False
3  6.0  NaN   True
4  8.0  9.0   True
```

```python
df.groupby("group").sum()
```
```
         v1   v2
group
False   2.0  9.0
True   14.0  9.0
```

# the solution

We should `raise ValueError()` by default when inputs are `nan`, but allow for this behavior to be recovered if possible? I don't think that silently passing over the missing data is statistically valid.... if we keep the [divide-by-*k* in line 116](https://github.com/pysal/esda/blob/master/esda/geary_local_mv.py#L116). However, if we replace that with `adj_list_gs.mean(axis=1).values`, then I think this is "valid" insofar as it may compute an average over a different number of squared difference for each site.

**Comment by jGaboardi** [comment]
Closed by #196
