### ISSUE TITLE
Matpotlib is a required dependency to import esda but it is not listed on the requirements

### ISSUE THREAD

**Issue by ocefpaf** [pysal/esda#216]
Based on https://github.com/pysal/esda/search?q=matplotlib we should probably add matplitlib as a required dependency.

**Comment by ljwolf** [comment]
I think the inclusion in topo.py is accidental, and can be removed. The other inclusions are for testing matrices, and in code that isn't run on import... I think we'd prefer to avoid it as a hard depends if possible!
