### ISSUE TITLE
no `varnames` in `Moran_BV_matrix`

### ISSUE THREAD

**Issue by slumnitz** [pysal/esda#22]
[`Moran_BV_matrix`](https://github.com/pysal/esda/blob/56aa85bc7327beb3d442d91b42d1457ce98f6e48/esda/moran.py#L454) object takes `varnames` as input, but this argument does not seem to be used anywhere in the function.

For labeling [`moran_facette()` plots](https://github.com/slumnitz/splot/blob/facette/notebooks/moran_…) (starting to prototype facets), it would be great to either include this list as an attribute of the `Moran-BV_matrix` Object, or even allow for `varnames` input in the `Moran_BV` Object. 

What do you think @sjsrey @darribas @ljwolf?

**Comment by ljwolf** [comment]
I think it'd be great to store the `varnames` on the object and use them when needed. By default these should be `['x{}'.format(i) for i in range(p)]` for an `(n,p)` input matrix.

**Comment by slumnitz** [comment]
Thank you for the tip: #23 should deal with this

**Comment by slumnitz** [comment]
This can be closed since #23 got merged.
