### ISSUE TITLE
`w.id_order` being included in calculation of multivariate local Geary C

### ISSUE THREAD

**Issue by realitychemist** [pysal/esda#241]
Basically, when calculating the multivariate local C statistic using `geary_local_mv`, there is a line that performs a sum across columns to get the statistic for each entry.  However, prior to performing this sum, a column is added to the dataframe which contains the IDs from `w.id_order`, and this index is being included in the sum!

The offending bit of source code is in the `_statistic` static method of `geary_local_mv`:

https://github.com/pysal/esda/blob/b0f7aa5daa6570be54f7da2c562aee6043e7b7b9/esda/geary_local_mv.py#L130-L135

The bug is on the last line before the return (line 133): `sum(axis=1)` sums across all columns, including the column `"w_order"` which was added on line 131.  A quick-and-dirty fix is to instead do this:
```py
localG = np.array(adj_list_gs[:, :-1].sum(axis=1, numeric_only=True) / k)
```
to simply omit the final column which contains the indices.  (**Edit:** sorry, you also need to convert `adj_list_gs` to an ndarray first to use slice indexing like that, I forgot I did this while testing; if you do that you also can't use the `numeric_only` flag, which is probably another reason not to actually fix it this way.)

This seems to give the correct C values, but it's definitely a bit of a hacky solution.  It would probably make more sense not to include `w.id_order` as its own column in the dataframe in the first place, or do an in-place drop of that column before summing.

I don't know if this is related to pysal/esda#239 or not, nor do I know whether this bug is affecting other Geary methods.  I just happened to notice this when I was getting absurdly small values of `p_sim` for my dataset (around `10e-05`).

**Comment by jGaboardi** [comment]
@sjsrey's PR – https://github.com/pysal/libpysal/pull/516) – will assist with debugging attempts.

**Comment by knaaptime** [comment]
Thanks for the report. We're in the process of deprecating `id_order`, and will be sure to look at this more closely

It sounds like you're not currently using a meaningful index for your observations (so you're getting a range index, which converts to numeric). Could you try setting a character index or similar before creating your W? That would ensure that your ids dont get added because the column isn't numeric

**Comment by realitychemist** [comment]
> It sounds like you're not currently using a meaningful index for your observations

You're right, I'm not!  There aren't any especially physically meaningful labels for my observations, but if I just cast the integer IDs to strings before I construct the weights object it does indeed avoid this issue.

**Comment by knaaptime** [comment]
Cool, thanks for checking. It should be pretty easy to include that logic rather than dropping the last column. Will look into it :)

**Comment by jeffcsauer** [comment]
@knaaptime @sjsrey on my radar! Happy to address.
