### ISSUE TITLE
More float precision on p values

### ISSUE THREAD

**Issue by mousepixels** [pysal/esda#243]
Hi! Would it be possible to change your stats that use 1 - stats.norm.cdf() to stats.norm.sf() to increase the p value float precision?

for example, morans.py line 170/171

**Comment by ljwolf** [comment]
Sure! Out of curiosity, which p value doesn’t have enough precision? If you’re looking at p_sim, that only depends on the number of permutations, not the normal cdf… use more permutations to achieve higher precision.

**Comment by mousepixels** [comment]
Hi! Thank you! Saves me from editing it every time i install in different environment xD

I am mostly concerned with Moran's so that is the only one I know of. Not sure if the 1 - cdf is used anywhere else in the package.

**Comment by ljwolf** [comment]
Right! So all Moran classes have multiple different p values provided. The only one that encounters the stats.norm.cdf() is the p_z_sim, which is generally not as well behaved as what we encourage users to use, p_sim. 

https://github.com/pysal/esda/blob/main/esda/moran.py#L190

That’s unaffected by the cdf… hence my question! Are you using p_z_sim?

**Comment by mousepixels** [comment]
Oh, sorry misunderstood your previous comment. No, I am using the p_norm.

https://github.com/pysal/esda/blob/7f831081c987e0d4bcf810c78b80519569694e9f/esda/moran.py#L171

**Comment by ljwolf** [comment]
OK, I've submitted a fix to swap to the survival function throughout. I would recommend, however, using `p_sim` instead of `p_norm`, especially in cases where you're using the local statistics.
