### ISSUE TITLE
What is Altman (1998)?

### ISSUE THREAD

**Issue by martinfleis** [pysal/esda#247]
Hey, I am using some of the shape stats in a paper and am trying to find the Altman (1998) reference that is all over the place in there. But haven't found it... Do you have a link? Is it a paper, software or what? We should probably properly include it in ` _static/references.bib`. 

cc @ljwolf

**Comment by ljwolf** [comment]
It's Micah Altman's PhD Thesis. Will find.

**Comment by ljwolf** [comment]
```
Altman, Micah (1998) Districting Principles and Democratic Representation. Dissertation (Ph.D.), California Institute of Technology. doi:10.7907/7ZE9-TH19. https://resolver.caltech.edu/CaltechETD:etd-05192004-142452
```

**Comment by martinfleis** [comment]
Got it https://thesis.library.caltech.edu/1871/. Thanks! Will keep the issue open to add a proper citation.

**Comment by ljwolf** [comment]
Thank you! I wrote the [shape stuff for a separate package from my PhD](https://github.com/ljwolf/shapestats), before I knew about sphinx referencing... I think the stuff that remains in there has your correctly-referenced material from momepy plus the other measures from `shapestats`.
