### ISSUE TITLE
adbscan test failures

### ISSUE THREAD

**Issue by sjsrey** [pysal/esda#254]
The [failures](https://github.com/pysal/esda/actions/runs/5685901231/job/15411739786#step:7:547) are related to an issue in [scikit-learn](https://github.com/scikit-learn/scikit-learn/pull/26772/files) which looks like it has been fixed in main and will be out in version 1.3.1.

**Comment by martinfleis** [comment]
Closing as it was fixed in upstream as shown in our dev CI.
