### ISSUE TITLE
release

### ISSUE THREAD

**Issue by martinfleis** [pysal/esda#262]
I would like to get out a release of esda that includes removal of pygeos (#244). Is there any blocker? Maybe #261?

Who is a release manager for esda? @ljwolf? I can take care of it if needed, assuming the release infrastructure is up to date (@jGaboardi?).

**Comment by ljwolf** [comment]
Happy to cut a release myself, and yes I was certainly hoping to finish #261 for a release. I haven't looked into the source of the `/vsi` `fiona` errors yet...

#259 would also be cool, but I don't think that will be ready.

**Comment by jGaboardi** [comment]
> assuming the release infrastructure is up to date (@jGaboardi?).

Yes, I believe the release infra is up-to-date.

**Comment by jGaboardi** [comment]
https://github.com/pysal/esda/pull/272#issuecomment-1777306010

**Comment by martinfleis** [comment]
2.5.0 that was discussed here is already out.

**Comment by jGaboardi** [comment]
Ah, yeah.

**Comment by jGaboardi** [comment]
So let's close this.
