### ISSUE TITLE
Feature request: allow for linewidth and edgecolor to be included as kwargs in lisa_cluster

### ISSUE THREAD

**Issue by CarrascoCesar** [pysal/esda#278]
Currently Lisa_cluster hard-codes linewidth and edgecolor and it would be nice to allow these parameters to be defined as kwargs.

**Comment by martinfleis** [comment]
I believe it is on the roadmap for the next release or the one after. We have just add an interactive plotting which exposes all of customisation in #274 and static version of the same should shortly follow.

**Comment by CarrascoCesar** [comment]
Thanks Martin!  Looking forward to the next releases.
