### ISSUE TITLE
Importing esda: need for update on numpy long

### ISSUE THREAD

**Issue by giuliaulpiani** [pysal/esda#284]
Dear all,
I have just installed esda on my Anaconda Prompt. When using Jupyter notebook and running the command "import esda" I get this error "module 'numpy' has no attribute 'long'". This happens because numpy.long was deprecated in numpy 1.20 and it is removed in numpy 1.24 (we would need to have numpy.longlong). See here: https://stackoverflow.com/questions/76389395/attributeerror-module-numpy-has-no-attribute-long.
Can this be fixed on the esda side? Otherwise a downgrade of both numpy and pandas would be needed, which is not ideal.
Many thanks,

Giulia

**Comment by martinfleis** [comment]
@giuliaulpiani which version of esda do you have? Can you show the full traceback? I believe that all of these compatibility issues have been fixed and if using the latest versions of the package from the PySAL ecosystem, you should not run into these.

**Comment by giuliaulpiani** [comment]
Hi Martin, many thanks for your quick reply. I installed it today and if I look at my pip list, I see esda 2.5.1. This is the latest version it seems. 
<img width="260" alt="image" src="https://github.com/pysal/esda/assets/75661189/cd8958c4-4364-4954-b86d-ba9fb258cd92">
This is what I get in the Jupyter environment:
<img width="575" alt="image" src="https://github.com/pysal/esda/assets/75661189/70928592-ec8c-4390-8895-a69d04a00d91">
<img width="564" alt="image" src="https://github.com/pysal/esda/assets/75661189/ee025766-da46-45fd-97a6-387c57d92919">

I have restarted the kernel a zillion times, but I always get the same error.
Any help is most appreciated

**Comment by martinfleis** [comment]
As shown in the Traceback , the error does not come from `esda` but from `numba` (used by `libpysal` which is used by `esda`). It may be that numba is not up to date. I any case, nothing we can solve on our side.
