### ISSUE TITLE
311-dev CI failures [2024-03-16]

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#285]
Current [failures in 311-dev CI](https://github.com/pysal/esda/actions/runs/8302862203/job/22725973349#step:7:612) are due to a fiona/geopandas compatibility issue that is being resolved in https://github.com/geopandas/geopandas/pull/3209. @martinfleis recommend ignoring. Creating this issue merely for sanity check.

* xref: https://github.com/pysal/spaghetti/issues/762

**Comment by martinfleis** [comment]
Resolved in upstream.
