### ISSUE TITLE
A-DBSCAN citation not generated in docs 

### ISSUE THREAD

**Issue by JosiahParry** [pysal/esda#287]
The A-DBSCAN algorithm's citation does not make it to the documentation. 

Any chance you can share the title of the paper? 😉 

https://github.com/pysal/esda/blob/a296c3945c289ca0f8c4b58f734493f4616ff606/esda/adbscan.py#L24C39-L24C55

<img width="356" alt="image" src="https://github.com/pysal/esda/assets/13534508/4b7efbbf-26ed-4ef7-8dbd-28469cad0220">

**Comment by martinfleis** [comment]
https://www.sciencedirect.com/science/article/pii/S0094119019300944

**Comment by JosiahParry** [comment]
Thank you, @martinfleis !!!
