### ISSUE TITLE
list `rtree` in optional requirements?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#304]
`rtree` seems to be an optional dependency for `esda` and required to use [`topo.isolation()`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/esda/topo.py#L121-L125), but it never made it into:
* [`pyproject.toml`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/pyproject.toml#L44)
* [`ci/310-numba.yaml`](https://github.com/pysal/esda/blob/main/ci/310-numba.yaml)
* [`environment.yml`](https://github.com/pysal/esda/blob/main/environment.yml)

Moreover, it is listed as hard dependency in the other CI envs (e.g. [`ci/310.yaml`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/ci/310.yaml#L17)), not an optional one.

So I supposed the first Q is: Is `rtree` a hard dependency or not? I supposed not, be we should come to consensus.

xref #301

**Comment by martinfleis** [comment]
Ideally it should not be given it is compiled and is no longer coming with geopandas.

**Comment by jGaboardi** [comment]
> Ideally it should not be given it is compiled and is no longer coming with geopandas.

**Should not** be a *hard* dep, correct?

**Comment by martinfleis** [comment]
Yeah. Rtree should not be a hard dependency.
