### ISSUE TITLE
formatting -> drop `black` and adopt `ruff`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#308]
* run `ruff` formatting on codebase
* update files
  * `pyproject.toml`
  * add `pre-commit-config.yaml`
  * turn on pre-commit workflow in CI integration

**Comment by jGaboardi** [comment]
@martinfleis would you prefer I hold off on this until the `Graph` enhancement PRs are merged?

xref:
* https://github.com/pysal/esda/pull/296
* https://github.com/pysal/esda/pull/295
* https://github.com/pysal/esda/pull/293
* etc.

**Comment by martinfleis** [comment]
Yes, to avoid conflicts please.
