### ISSUE TITLE
move `geopandas` requirements

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#312]
Currently, `geopandas` is [list as a `testing` dependency](https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/pyproject.toml#L51), but we should probably move it to a new category since it can be imported for optional functionality in [`adbscan.get_cluster_boundary()`](https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/esda/adbscan.py#L509)

This will affect #307.

xref #311

**Comment by martinfleis** [comment]
It is a hard dependency for lib which is a hard dep for esda, no?

**Comment by jGaboardi** [comment]
> It is a hard dependency for lib which is a hard dep for esda, no?

Good point... `esda` is super out of date. LOL
