### ISSUE TITLE
determine minimal pin for `libpysal`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#319]
determine minimal pin for `libpysal` --> might need a `4.11.1` release and pin that.

* https://github.com/pysal/esda/pull/318#issue-2399280987
* https://github.com/pysal/esda/issues/299#issuecomment-2218370883

#### Edit

* Minimal pin will be `v4.12.0`

**Comment by martinfleis** [comment]
If we want to ensure full Graph support, it may need 4.12.

**Comment by jGaboardi** [comment]
I am very OK with that.

**Comment by jGaboardi** [comment]
For some reason I thought that already existed... I guess we'll need to cut a fresh `libpysal` for that.
