### ISSUE TITLE
weird Python 3.10 oldest error

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#331]
* We're seeing the weird intermittent lack of warnings error[^1][^2] again in the Python 3.10-oldest CI environment.
* Can't determine why it's not emitting warnings or why only in that environment
* Perhaps add an xfail for that test on  Python 3.10-oldest?

[^1]: https://github.com/pysal/esda/actions/runs/10020620559/job/27698396126#step:6:479
[^2]: https://github.com/pysal/esda/pull/326#issuecomment-2240041003

**Comment by martinfleis** [comment]
> Perhaps add an xfail for that test on Python 3.10-oldest?

+1

**Comment by jGaboardi** [comment]
We are now also seeing this in [CI (ubuntu-latest, ci/312-min.yaml](https://github.com/pysal/esda/actions/runs/10021614473/job/27700485665?pr=332#step:6:561)

**Comment by jGaboardi** [comment]
Other errors are cropping up, seemingly related to the `W` parameter set... xref #338
