### ISSUE TITLE
unused `zx` in `moran.Moran_Local_BV.__calc()`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#333]
Seems the `zx` argument is not needed in `moran.Moran_Local_BV.__calc()` since it is accessed through the class attribute.

https://github.com/pysal/esda/blob/6c34d273ad9b9a5d6df4e328b97e45a9b17e5f03/esda/moran.py#L1432-L1434

Can I get a confirmation on this?

xref #332

**Comment by sjsrey** [comment]
We could rewrite:
```
def __calc(self, w, zx, zy): 
     zly = _slag(w, zy) 
     return self.n_1 * self.zx * zly / self.den 
```
to 
```
def __calc(self): 
     zly = _slag(self.w, self.zy) 
     return self.n_1 * self.zx * zly / self.den 
```
and then update https://github.com/pysal/esda/blob/6c34d273ad9b9a5d6df4e328b97e45a9b17e5f03/esda/moran.py#L1399
to be
```
        self.Is = self.__calc()
```

**Comment by jGaboardi** [comment]
I will do that following #332
