### ISSUE TITLE
declared but unused `xtyt` & `xhyh` in `shape._second_moa_ring_xplusy()`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#334]
The `xtyt` & `xhyh` are declared within `shape._second_moa_ring_xplusy()` but not actually used in any calculation. Not sure if they can simply be removed or if the is a bug that has been affecting results.

https://github.com/pysal/esda/blob/6c34d273ad9b9a5d6df4e328b97e45a9b17e5f03/esda/shape.py#L582-L602

xref #332 

@martinfleis @ljwolf

**Comment by martinfleis** [comment]
I think it is safe to remove.
