### ISSUE TITLE
Data missing from example notebooks

### ISSUE THREAD

**Issue by sjsrey** [pysal/esda#49]
[Example nb](https://github.com/pysal/esda/blob/master/notebooks/Spatial%20Autocorrelation%20for%20Areal%20Unit%20Data.ipynb) uses data that was creaated in geopython workshop but not included in this repos.

**Comment by darribas** [comment]
+1 just run into this when updating notebook for the `Smaup` example ([#659d734b0f204e620845fc8e294905aeb69107eb](https://github.com/JuancaDuque/esda/pull/2/commits/659d734b0f204e620845fc8e294905aeb69107eb))

**Comment by sjsrey** [comment]
Closed with #75
