### ISSUE TITLE
esda 2.0.1 is release on github, but not on pypi

### ISSUE THREAD

**Issue by weikang9009** [pysal/esda#56]
It seems that esda 2.0.1 was [release on github](https://github.com/pysal/esda/releases/tag/v2.0.1), but [not on pypi](https://pypi.org/project/esda/)

**Comment by jGaboardi** [comment]
@weikang9009 @sjsrey Can this be closed since `esda` is available at [v2.1.1](https://pypi.org/project/esda/2.1.1/ )?
