### ISSUE TITLE
(BUG) esda 2.1.0 on pypi cannot be installed

### ISSUE THREAD

**Issue by weikang9009** [pysal/esda#65]
[giddy travis ci testing runs into the following error]( https://travis-ci.org/pysal/giddy/jobs/552595230):
![image](https://user-images.githubusercontent.com/7359284/60412217-2c6ff080-9b85-11e9-90c6-23140427c9b5.png)
Seems to be some issue related to [esda's new release on pypi](https://pypi.org/project/esda/)

When I tried to install the new version locally by running `pip install -U esda`, I ran into the same error:
![image](https://user-images.githubusercontent.com/7359284/60412302-6e993200-9b85-11e9-8dec-f2dd8422a181.png)

**Comment by ocefpaf** [comment]
`setup.py` expects a `README.md` but the source distribution renamed it to `README.rst`. I'll raise upstream.

xref.: https://github.com/conda-forge/esda-feedstock/pull/3
