### ISSUE TITLE
PySAL development guidelines link broken in pysal/esda

### ISSUE THREAD

**Issue by matthewborish** [pysal/esda#73]
PySAL development guidelines link under contributions heading is broken on https://github.com/pysal/esda.

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

**Comment by sjsrey** [comment]
This also impacts [the meta package](https://pysal.readthedocs.io/en/latest/).

The correct link is https://github.com/pysal/pysal/wiki.
