### ISSUE TITLE
no output in documentation notebooks

### ISSUE THREAD

**Issue by apoorvalal** [pysal/esda#82]
Can someone who has access to the data run the [example notebook on the website](https://nbviewer.jupyter.org/github/pysal/esda/blob/master/notebooks/Spatial%20Autocorrelation%20for%20Areal%20Unit%20Data.ipynb) ? There is no output at the moment, which sort of defeats the purpose.

Thanks for the great package!

**Comment by sjsrey** [comment]
Thanks for reporting this, will be fixed shortly.

You may also be interested in the [broader notebook project](http://pysal.org/notebooks/intro), with the understanding that it is a work in progress.
